version: '3'
services:
  web: 
    build: .
    environment:
      - ENVIRONMENT=docker
    env_file: 
      - .env 
    ports:
      - "7070:7070"
    volumes:
    - type: bind
      source: ./gkey.json
      target: /app/gkey.json