apiVersion: apps/v1
kind: Deployment
metadata:
  name: elysium-deployment
  labels:
    app: elysium
spec:
  selector:
    matchLabels:
      app: elysium
  template:
    metadata:
      labels:
        app: elysium
    spec:
      containers:
        - name: elysium
          image: ghcr.io/nick-ducker/elysium:latest
          imagePullPolicy: Always
          ports: 
          - containerPort: 8080
          envFrom:
          - secretRef: 
              name: elysium-secrets
      imagePullSecrets: 
        - name: dockerconfigjson-github-com